// Theme registry: each entry fully overrides the CSS custom properties defined
// as defaults in theme.css. Applying a theme just walks `vars` and calls
// documentElement.style.setProperty for each - no per-theme CSS blocks needed.

export interface ThemeDefinition {
  id: string
  name: string
  tagline: string
  swatch: [string, string, string] // bg, accent, gold - used for the picker preview dot
  vars: Record<string, string>
}

const SHARED_FONTS = {
  '--font-heading': "'Cinzel', serif",
  '--font-body': "'IM Fell English', Georgia, serif",
}

export const THEMES: ThemeDefinition[] = [
  {
    id: 'parchment',
    name: 'Parchment',
    tagline: 'Classic tabletop parchment & ink',
    swatch: ['#ece0c4', '#6e1f22', '#a9791f'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'Cinzel Decorative', 'Cinzel', serif",
      '--color-parchment': '#ece0c4',
      '--color-parchment-dark': '#ddc99e',
      '--color-parchment-shadow': '#c9b384',
      '--color-parchment-panel': '#f4ead2',
      '--color-ink': '#2a1e14',
      '--color-ink-soft': '#4a3826',
      '--color-wine': '#6e1f22',
      '--color-wine-bright': '#8f2a2e',
      '--color-forest': '#33502f',
      '--color-gold': '#a9791f',
      '--color-gold-bright': '#c99a3a',
      '--color-border': '#7a5a34',
      '--color-border-soft': '#b79a68',
      '--color-danger': '#7a2020',
      '--color-danger-bright': '#a53030',
      '--color-success': '#33502f',
      '--color-on-wine': '#f4ead2',
      '--color-on-gold': '#2a1e14',
      '--color-on-danger': '#f4ead2',
    },
  },
  {
    id: 'monk',
    name: 'Monk',
    tagline: 'Jade serenity & bamboo calm',
    swatch: ['#e8ede4', '#2f6e4f', '#b08a3e'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'Cinzel', serif",
      '--color-parchment': '#e8ede4',
      '--color-parchment-dark': '#d3ddd0',
      '--color-parchment-shadow': '#b9c7b5',
      '--color-parchment-panel': '#f2f5ee',
      '--color-ink': '#1f2e1f',
      '--color-ink-soft': '#3f5240',
      '--color-wine': '#2f6e4f',
      '--color-wine-bright': '#3f8a63',
      '--color-forest': '#5c7a4f',
      '--color-gold': '#b08a3e',
      '--color-gold-bright': '#c9a55c',
      '--color-border': '#5c7a56',
      '--color-border-soft': '#9db393',
      '--color-danger': '#8a3b2e',
      '--color-danger-bright': '#b34d3a',
      '--color-success': '#2f6e4f',
      '--color-on-wine': '#f2f5ee',
      '--color-on-gold': '#1f2e1f',
      '--color-on-danger': '#f2f5ee',
    },
  },
  {
    id: 'assassin',
    name: 'Assassin',
    tagline: 'Midnight steel & blood-red edge',
    swatch: ['#17181a', '#8a1620', '#8a8f98'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'Pirata One', 'Cinzel', serif",
      '--color-parchment': '#17181a',
      '--color-parchment-dark': '#0f1011',
      '--color-parchment-shadow': '#000000',
      '--color-parchment-panel': '#212226',
      '--color-ink': '#e8e3df',
      '--color-ink-soft': '#a8a29b',
      '--color-wine': '#a3222d',
      '--color-wine-bright': '#c73641',
      '--color-forest': '#3a3d42',
      '--color-gold': '#8a8f98',
      '--color-gold-bright': '#b7bcc4',
      '--color-border': '#3a3d42',
      '--color-border-soft': '#55585e',
      '--color-danger': '#a3222d',
      '--color-danger-bright': '#c73641',
      '--color-success': '#3f7a4e',
      '--color-on-wine': '#f5f0e5',
      '--color-on-gold': '#14100c',
      '--color-on-danger': '#f5f0e5',
    },
  },
  {
    id: 'bard',
    name: 'Bard',
    tagline: 'Theatrical purple & gilded gold',
    swatch: ['#f1e6f5', '#7b2d8e', '#c9932f'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'Fondamento', 'Cinzel', serif",
      '--color-parchment': '#f1e6f5',
      '--color-parchment-dark': '#ddc7e6',
      '--color-parchment-shadow': '#c7a8d4',
      '--color-parchment-panel': '#f8f0fa',
      '--color-ink': '#2e1a35',
      '--color-ink-soft': '#54405c',
      '--color-wine': '#7b2d8e',
      '--color-wine-bright': '#9a3fad',
      '--color-forest': '#4a2e5c',
      '--color-gold': '#c9932f',
      '--color-gold-bright': '#e0ac4c',
      '--color-border': '#8a5a97',
      '--color-border-soft': '#c19fcb',
      '--color-danger': '#8e2d3f',
      '--color-danger-bright': '#b23c53',
      '--color-success': '#3d7a4f',
      '--color-on-wine': '#f8f0fa',
      '--color-on-gold': '#2e1a35',
      '--color-on-danger': '#f8f0fa',
    },
  },
  {
    id: 'wizard',
    name: 'Wizard',
    tagline: 'Arcane indigo & moonlit silver',
    swatch: ['#161c2e', '#4d5fd1', '#8fd6e8'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'Uncial Antiqua', 'Cinzel', serif",
      '--color-parchment': '#161c2e',
      '--color-parchment-dark': '#101523',
      '--color-parchment-shadow': '#0a0d18',
      '--color-parchment-panel': '#1f2740',
      '--color-ink': '#dfe4f5',
      '--color-ink-soft': '#9aa4c4',
      '--color-wine': '#4d5fd1',
      '--color-wine-bright': '#6b7ce8',
      '--color-forest': '#2e3a63',
      '--color-gold': '#8fd6e8',
      '--color-gold-bright': '#b0e6f2',
      '--color-border': '#3a4468',
      '--color-border-soft': '#4f5b86',
      '--color-danger': '#c4455a',
      '--color-danger-bright': '#dd5f73',
      '--color-success': '#4fa87e',
      '--color-on-wine': '#f5f0e5',
      '--color-on-gold': '#0d1420',
      '--color-on-danger': '#f5f0e5',
    },
  },
  {
    id: 'goliath',
    name: 'Goliath',
    tagline: 'Sunbaked stone & burnt rust',
    swatch: ['#e6ddd0', '#b0501f', '#8a7048'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'MedievalSharp', 'Cinzel', serif",
      '--color-parchment': '#e6ddd0',
      '--color-parchment-dark': '#d5c7b2',
      '--color-parchment-shadow': '#bfab8d',
      '--color-parchment-panel': '#efe7db',
      '--color-ink': '#2b2420',
      '--color-ink-soft': '#5a4f45',
      '--color-wine': '#b0501f',
      '--color-wine-bright': '#d16a34',
      '--color-forest': '#5f5138',
      '--color-gold': '#8a7048',
      '--color-gold-bright': '#a88c5f',
      '--color-border': '#8a7048',
      '--color-border-soft': '#b39d78',
      '--color-danger': '#8a2e1f',
      '--color-danger-bright': '#b03d29',
      '--color-success': '#4c6a3a',
      '--color-on-wine': '#efe7db',
      '--color-on-gold': '#2b2420',
      '--color-on-danger': '#efe7db',
    },
  },
  {
    id: 'dwarf',
    name: 'Dwarf',
    tagline: 'Deep-forge copper & soot stone',
    swatch: ['#241d18', '#b5651d', '#c98a3a'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'MedievalSharp', 'Cinzel', serif",
      '--color-parchment': '#241d18',
      '--color-parchment-dark': '#1a1512',
      '--color-parchment-shadow': '#100d0b',
      '--color-parchment-panel': '#302722',
      '--color-ink': '#eee0cf',
      '--color-ink-soft': '#b8a58e',
      '--color-wine': '#b5651d',
      '--color-wine-bright': '#d97f34',
      '--color-forest': '#4a3d2e',
      '--color-gold': '#c98a3a',
      '--color-gold-bright': '#e0a558',
      '--color-border': '#5a4636',
      '--color-border-soft': '#7a6350',
      '--color-danger': '#a3402a',
      '--color-danger-bright': '#c2543b',
      '--color-success': '#6a8a4a',
      '--color-on-wine': '#1a1108',
      '--color-on-gold': '#1a1108',
      '--color-on-danger': '#f5f0e5',
    },
  },
  {
    id: 'ranger',
    name: 'Ranger',
    tagline: 'Mossy woodland & wild-track green',
    swatch: ['#eef0e4', '#3f6b2e', '#8a9c4a'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'MedievalSharp', 'Cinzel', serif",
      '--color-parchment': '#eef0e4',
      '--color-parchment-dark': '#dbe0cb',
      '--color-parchment-shadow': '#c3cba9',
      '--color-parchment-panel': '#f5f6ec',
      '--color-ink': '#22301c',
      '--color-ink-soft': '#48583e',
      '--color-wine': '#3f6b2e',
      '--color-wine-bright': '#528a3d',
      '--color-forest': '#6b5a35',
      '--color-gold': '#8a9c4a',
      '--color-gold-bright': '#a3b562',
      '--color-border': '#6b7d4a',
      '--color-border-soft': '#a3b483',
      '--color-danger': '#8a3b2e',
      '--color-danger-bright': '#b34d3a',
      '--color-success': '#3f6b2e',
      '--color-on-wine': '#f5f6ec',
      '--color-on-gold': '#22301c',
      '--color-on-danger': '#f5f6ec',
    },
  },
  {
    id: 'paladin',
    name: 'Paladin',
    tagline: 'Radiant gold & royal-oath blue',
    swatch: ['#f7f3e3', '#25528a', '#c9a227'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'Cinzel Decorative', 'Cinzel', serif",
      '--color-parchment': '#f7f3e3',
      '--color-parchment-dark': '#ecdfba',
      '--color-parchment-shadow': '#d9c483',
      '--color-parchment-panel': '#fffaf0',
      '--color-ink': '#2b2410',
      '--color-ink-soft': '#5c5030',
      '--color-wine': '#25528a',
      '--color-wine-bright': '#3a6fad',
      '--color-forest': '#5c5030',
      '--color-gold': '#c9a227',
      '--color-gold-bright': '#e0bd4c',
      '--color-border': '#b89a4a',
      '--color-border-soft': '#d9c483',
      '--color-danger': '#8a2e2e',
      '--color-danger-bright': '#b03d3d',
      '--color-success': '#3d7a4f',
      '--color-on-wine': '#fffaf0',
      '--color-on-gold': '#2b2410',
      '--color-on-danger': '#fffaf0',
    },
  },
  {
    id: 'sorcerer',
    name: 'Sorcerer',
    tagline: 'Wild chaos magenta & fire orange',
    swatch: ['#1f1526', '#c23fa0', '#ff8a3d'],
    vars: {
      ...SHARED_FONTS,
      '--font-display': "'Fondamento', 'Cinzel', serif",
      '--color-parchment': '#1f1526',
      '--color-parchment-dark': '#170f1c',
      '--color-parchment-shadow': '#0d0912',
      '--color-parchment-panel': '#2b1e35',
      '--color-ink': '#f0e0f5',
      '--color-ink-soft': '#b89ac4',
      '--color-wine': '#c23fa0',
      '--color-wine-bright': '#dd5cbc',
      '--color-forest': '#4a2e5c',
      '--color-gold': '#ff8a3d',
      '--color-gold-bright': '#ffa85f',
      '--color-border': '#5c3d6e',
      '--color-border-soft': '#7a5a8e',
      '--color-danger': '#c23f3f',
      '--color-danger-bright': '#dd5c5c',
      '--color-success': '#3fae7a',
      '--color-on-wine': '#1f1526',
      '--color-on-gold': '#1f1526',
      '--color-on-danger': '#f5f0e5',
    },
  },
]

export const DEFAULT_THEME_ID = 'parchment'

export function getTheme(id: string): ThemeDefinition {
  return THEMES.find((t) => t.id === id) ?? THEMES[0]
}

export function applyTheme(id: string): void {
  const theme = getTheme(id)
  const root = document.documentElement
  for (const [key, value] of Object.entries(theme.vars)) {
    root.style.setProperty(key, value)
  }
  root.dataset.theme = theme.id
}
